import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

function fmt(n: number) {
  return new Intl.NumberFormat("en-US", { maximumFractionDigits: 2 }).format(n);
}

interface Tx { amount: number; direction: string; transaction_date: string; details: string | null; currency_id: string }
interface Currency { id: string; name: string; rate: number }

// NOTE: Arabic shaping in jsPDF requires a font with Arabic glyphs.
// We render labels in English for the headers + person name in Arabic body cells.
// jsPDF default font handles RTL Arabic poorly, so we use a neutral layout:
// keep numeric/date columns LTR and Arabic text in the rightmost column.

export function exportPersonStatementPDF(opts: {
  personName: string;
  phone?: string | null;
  txs: Tx[];
  currencies: Currency[];
  balance: number;
}) {
  const { personName, phone, txs, currencies, balance } = opts;
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });

  doc.setFontSize(18);
  doc.text("Statement of Account / كشف حساب", 105, 15, { align: "center" });
  doc.setFontSize(11);
  doc.text(`Name: ${personName}`, 15, 28);
  if (phone) doc.text(`Phone: ${phone}`, 15, 34);
  doc.text(`Date: ${new Date().toLocaleDateString("en-GB")}`, 15, phone ? 40 : 34);

  const ordered = [...txs].sort(
    (a, b) => new Date(a.transaction_date).getTime() - new Date(b.transaction_date).getTime(),
  );
  let acc = 0;
  const rows = ordered.map((t) => {
    const cur = currencies.find((c) => c.id === t.currency_id);
    const signed = Number(t.amount) * (t.direction === "credit" ? 1 : -1) * (cur?.rate ?? 1);
    acc += signed;
    return [
      new Date(t.transaction_date).toLocaleDateString("en-GB"),
      t.direction === "credit" ? "Credit" : "Debit",
      fmt(Number(t.amount)),
      cur?.name ?? "",
      fmt(acc),
      t.details ?? "",
    ];
  });

  autoTable(doc, {
    startY: phone ? 46 : 40,
    head: [["Date", "Type", "Amount", "Currency", "Balance", "Details"]],
    body: rows,
    styles: { fontSize: 9, cellPadding: 2 },
    headStyles: { fillColor: [37, 99, 235], halign: "center" },
    columnStyles: { 5: { halign: "right" } },
  });

  // Footer balance
  const y = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 8;
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  const status = balance >= 0 ? "Owed to you" : "You owe";
  doc.text(`Final Balance: ${fmt(Math.abs(balance))}  (${status})`, 15, y);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.text("Generated by Daftarak", 105, 285, { align: "center" });

  doc.save(`statement-${personName}-${Date.now()}.pdf`);
}
