/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppRemindersRouteImport } from './routes/app.reminders'
import { Route as AppRecurringRouteImport } from './routes/app.recurring'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppInsightsRouteImport } from './routes/app.insights'
import { Route as AppExpensesRouteImport } from './routes/app.expenses'
import { Route as AppCurrenciesRouteImport } from './routes/app.currencies'
import { Route as AppCategoriesRouteImport } from './routes/app.categories'
import { Route as AppBudgetsRouteImport } from './routes/app.budgets'
import { Route as AppArchiveRouteImport } from './routes/app.archive'
import { Route as AppActivityRouteImport } from './routes/app.activity'
import { Route as AppSettingsSecurityRouteImport } from './routes/app.settings.security'
import { Route as AppSettingsProfileRouteImport } from './routes/app.settings.profile'
import { Route as AppSettingsNotificationsRouteImport } from './routes/app.settings.notifications'
import { Route as AppSettingsDataRouteImport } from './routes/app.settings.data'
import { Route as AppSettingsAppearanceRouteImport } from './routes/app.settings.appearance'
import { Route as AppSettingsAboutRouteImport } from './routes/app.settings.about'
import { Route as AppPersonIdRouteImport } from './routes/app.person.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppRemindersRoute = AppRemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => AppRoute,
} as any)
const AppRecurringRoute = AppRecurringRouteImport.update({
  id: '/recurring',
  path: '/recurring',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppInsightsRoute = AppInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AppRoute,
} as any)
const AppExpensesRoute = AppExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AppRoute,
} as any)
const AppCurrenciesRoute = AppCurrenciesRouteImport.update({
  id: '/currencies',
  path: '/currencies',
  getParentRoute: () => AppRoute,
} as any)
const AppCategoriesRoute = AppCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AppRoute,
} as any)
const AppBudgetsRoute = AppBudgetsRouteImport.update({
  id: '/budgets',
  path: '/budgets',
  getParentRoute: () => AppRoute,
} as any)
const AppArchiveRoute = AppArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => AppRoute,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsSecurityRoute = AppSettingsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsProfileRoute = AppSettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsNotificationsRoute =
  AppSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AppSettingsRoute,
  } as any)
const AppSettingsDataRoute = AppSettingsDataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsAppearanceRoute = AppSettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsAboutRoute = AppSettingsAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppPersonIdRoute = AppPersonIdRouteImport.update({
  id: '/person/$id',
  path: '/person/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/activity': typeof AppActivityRoute
  '/app/archive': typeof AppArchiveRoute
  '/app/budgets': typeof AppBudgetsRoute
  '/app/categories': typeof AppCategoriesRoute
  '/app/currencies': typeof AppCurrenciesRoute
  '/app/expenses': typeof AppExpensesRoute
  '/app/insights': typeof AppInsightsRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/recurring': typeof AppRecurringRoute
  '/app/reminders': typeof AppRemindersRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/person/$id': typeof AppPersonIdRoute
  '/app/settings/about': typeof AppSettingsAboutRoute
  '/app/settings/appearance': typeof AppSettingsAppearanceRoute
  '/app/settings/data': typeof AppSettingsDataRoute
  '/app/settings/notifications': typeof AppSettingsNotificationsRoute
  '/app/settings/profile': typeof AppSettingsProfileRoute
  '/app/settings/security': typeof AppSettingsSecurityRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/activity': typeof AppActivityRoute
  '/app/archive': typeof AppArchiveRoute
  '/app/budgets': typeof AppBudgetsRoute
  '/app/categories': typeof AppCategoriesRoute
  '/app/currencies': typeof AppCurrenciesRoute
  '/app/expenses': typeof AppExpensesRoute
  '/app/insights': typeof AppInsightsRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/recurring': typeof AppRecurringRoute
  '/app/reminders': typeof AppRemindersRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRouteWithChildren
  '/app': typeof AppIndexRoute
  '/app/person/$id': typeof AppPersonIdRoute
  '/app/settings/about': typeof AppSettingsAboutRoute
  '/app/settings/appearance': typeof AppSettingsAppearanceRoute
  '/app/settings/data': typeof AppSettingsDataRoute
  '/app/settings/notifications': typeof AppSettingsNotificationsRoute
  '/app/settings/profile': typeof AppSettingsProfileRoute
  '/app/settings/security': typeof AppSettingsSecurityRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/activity': typeof AppActivityRoute
  '/app/archive': typeof AppArchiveRoute
  '/app/budgets': typeof AppBudgetsRoute
  '/app/categories': typeof AppCategoriesRoute
  '/app/currencies': typeof AppCurrenciesRoute
  '/app/expenses': typeof AppExpensesRoute
  '/app/insights': typeof AppInsightsRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/recurring': typeof AppRecurringRoute
  '/app/reminders': typeof AppRemindersRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/person/$id': typeof AppPersonIdRoute
  '/app/settings/about': typeof AppSettingsAboutRoute
  '/app/settings/appearance': typeof AppSettingsAppearanceRoute
  '/app/settings/data': typeof AppSettingsDataRoute
  '/app/settings/notifications': typeof AppSettingsNotificationsRoute
  '/app/settings/profile': typeof AppSettingsProfileRoute
  '/app/settings/security': typeof AppSettingsSecurityRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/app/activity'
    | '/app/archive'
    | '/app/budgets'
    | '/app/categories'
    | '/app/currencies'
    | '/app/expenses'
    | '/app/insights'
    | '/app/notifications'
    | '/app/recurring'
    | '/app/reminders'
    | '/app/reports'
    | '/app/settings'
    | '/app/'
    | '/app/person/$id'
    | '/app/settings/about'
    | '/app/settings/appearance'
    | '/app/settings/data'
    | '/app/settings/notifications'
    | '/app/settings/profile'
    | '/app/settings/security'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app/activity'
    | '/app/archive'
    | '/app/budgets'
    | '/app/categories'
    | '/app/currencies'
    | '/app/expenses'
    | '/app/insights'
    | '/app/notifications'
    | '/app/recurring'
    | '/app/reminders'
    | '/app/reports'
    | '/app/settings'
    | '/app'
    | '/app/person/$id'
    | '/app/settings/about'
    | '/app/settings/appearance'
    | '/app/settings/data'
    | '/app/settings/notifications'
    | '/app/settings/profile'
    | '/app/settings/security'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/app/activity'
    | '/app/archive'
    | '/app/budgets'
    | '/app/categories'
    | '/app/currencies'
    | '/app/expenses'
    | '/app/insights'
    | '/app/notifications'
    | '/app/recurring'
    | '/app/reminders'
    | '/app/reports'
    | '/app/settings'
    | '/app/'
    | '/app/person/$id'
    | '/app/settings/about'
    | '/app/settings/appearance'
    | '/app/settings/data'
    | '/app/settings/notifications'
    | '/app/settings/profile'
    | '/app/settings/security'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reminders': {
      id: '/app/reminders'
      path: '/reminders'
      fullPath: '/app/reminders'
      preLoaderRoute: typeof AppRemindersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/recurring': {
      id: '/app/recurring'
      path: '/recurring'
      fullPath: '/app/recurring'
      preLoaderRoute: typeof AppRecurringRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/insights': {
      id: '/app/insights'
      path: '/insights'
      fullPath: '/app/insights'
      preLoaderRoute: typeof AppInsightsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/expenses': {
      id: '/app/expenses'
      path: '/expenses'
      fullPath: '/app/expenses'
      preLoaderRoute: typeof AppExpensesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/currencies': {
      id: '/app/currencies'
      path: '/currencies'
      fullPath: '/app/currencies'
      preLoaderRoute: typeof AppCurrenciesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/categories': {
      id: '/app/categories'
      path: '/categories'
      fullPath: '/app/categories'
      preLoaderRoute: typeof AppCategoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/budgets': {
      id: '/app/budgets'
      path: '/budgets'
      fullPath: '/app/budgets'
      preLoaderRoute: typeof AppBudgetsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/archive': {
      id: '/app/archive'
      path: '/archive'
      fullPath: '/app/archive'
      preLoaderRoute: typeof AppArchiveRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/activity': {
      id: '/app/activity'
      path: '/activity'
      fullPath: '/app/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings/security': {
      id: '/app/settings/security'
      path: '/security'
      fullPath: '/app/settings/security'
      preLoaderRoute: typeof AppSettingsSecurityRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/settings/profile': {
      id: '/app/settings/profile'
      path: '/profile'
      fullPath: '/app/settings/profile'
      preLoaderRoute: typeof AppSettingsProfileRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/settings/notifications': {
      id: '/app/settings/notifications'
      path: '/notifications'
      fullPath: '/app/settings/notifications'
      preLoaderRoute: typeof AppSettingsNotificationsRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/settings/data': {
      id: '/app/settings/data'
      path: '/data'
      fullPath: '/app/settings/data'
      preLoaderRoute: typeof AppSettingsDataRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/settings/appearance': {
      id: '/app/settings/appearance'
      path: '/appearance'
      fullPath: '/app/settings/appearance'
      preLoaderRoute: typeof AppSettingsAppearanceRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/settings/about': {
      id: '/app/settings/about'
      path: '/about'
      fullPath: '/app/settings/about'
      preLoaderRoute: typeof AppSettingsAboutRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/person/$id': {
      id: '/app/person/$id'
      path: '/person/$id'
      fullPath: '/app/person/$id'
      preLoaderRoute: typeof AppPersonIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppSettingsRouteChildren {
  AppSettingsAboutRoute: typeof AppSettingsAboutRoute
  AppSettingsAppearanceRoute: typeof AppSettingsAppearanceRoute
  AppSettingsDataRoute: typeof AppSettingsDataRoute
  AppSettingsNotificationsRoute: typeof AppSettingsNotificationsRoute
  AppSettingsProfileRoute: typeof AppSettingsProfileRoute
  AppSettingsSecurityRoute: typeof AppSettingsSecurityRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsAboutRoute: AppSettingsAboutRoute,
  AppSettingsAppearanceRoute: AppSettingsAppearanceRoute,
  AppSettingsDataRoute: AppSettingsDataRoute,
  AppSettingsNotificationsRoute: AppSettingsNotificationsRoute,
  AppSettingsProfileRoute: AppSettingsProfileRoute,
  AppSettingsSecurityRoute: AppSettingsSecurityRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppRouteChildren {
  AppActivityRoute: typeof AppActivityRoute
  AppArchiveRoute: typeof AppArchiveRoute
  AppBudgetsRoute: typeof AppBudgetsRoute
  AppCategoriesRoute: typeof AppCategoriesRoute
  AppCurrenciesRoute: typeof AppCurrenciesRoute
  AppExpensesRoute: typeof AppExpensesRoute
  AppInsightsRoute: typeof AppInsightsRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppRecurringRoute: typeof AppRecurringRoute
  AppRemindersRoute: typeof AppRemindersRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppPersonIdRoute: typeof AppPersonIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActivityRoute: AppActivityRoute,
  AppArchiveRoute: AppArchiveRoute,
  AppBudgetsRoute: AppBudgetsRoute,
  AppCategoriesRoute: AppCategoriesRoute,
  AppCurrenciesRoute: AppCurrenciesRoute,
  AppExpensesRoute: AppExpensesRoute,
  AppInsightsRoute: AppInsightsRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppRecurringRoute: AppRecurringRoute,
  AppRemindersRoute: AppRemindersRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppPersonIdRoute: AppPersonIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
